---
- hosts: active-directory
  gather_facts: True
  become: True
  roles:
    - role: SSH
      vars:
        port_number: 22
        log_level: INFO
        permit_root_login: no
        max_auth_tries: 3
        max_sessions: 3
        password_authentication: no
        allow_tunneling: no

    - role: BIND
      vars:
        dns_sec: yes

    - role: Samba-DC
      vars:
        samba_version: "4.13.2"
        domain_name: anet
        realm: anet.internal
        administrator_password: Passw@ord123!
        dns_backend: BIND9_DLZ