---
- hosts: active-directory
  gather_facts: True
  become: True
  roles:

    - role: BIND
      vars:
        forward_zone_name: anet.internal
        dns_sec: yes

    - role: Samba-DC
      vars:
        samba_version: "4.13.2"
        domain_name: anet
        realm: anet.internal
        administrator_password: Passw@ord123!
        dns_backend: BIND9_DLZ