---
- hosts: active-directory
  gather_facts: True
  become: True
  roles:

    - role: Samba-DC
      vars:
        samba_version: "4.13.2"
        domain_name: anet
        realm: anet.internal
        administrator_password: Passw@ord123!
