---
- name: Disable Network Manager from setting DNS
  shell: |
    echo '[main]' > /etc/NetworkManager/conf.d/90-dns-none.conf
    echo 'dns=none' >> /etc/NetworkManager/conf.d/90-dns-none.conf
    systemctl reload NetworkManager

- name: Install BIND
  dnf:
    name:
      - bind
      - bind-utils

- name: Download DNS root hints
  get_url:
    url: http://www.internic.net/zones/named.root
    dest: /var/named/named.root
    mode: 0640
    owner: root
    group: named

- name: Update named.conf
  template:
    src: templates/named.conf.j2
    dest: /etc/named.conf
    owner: named
    group: named
    mode: '0664'

- name: Disable Firewalld
  systemd:
    name: firewalld
    enabled: no
    state: stopped

- name: Enable BIND
  systemd:
    name: named
    enabled: yes
    state: stopped